### ISSUE TITLE
Bug when sending flash messages during registration

### ISSUE THREAD

**Issue by georgeben** [Princesso/Send-IT#69]
Hi @Princesso nice app! When I try to register without filling the input fields, I get the message: "An error occurred while trying to register you". If I consecutively tap on the Register button, the previous error doesn't clear off but a new one continues showing up. Attatched is a screen shot of what I mean.
![sent it issue](https://user-images.githubusercontent.com/40215996/50456089-5fc19080-0952-11e9-8f07-3780dff4cbb3.PNG)

**Comment by Princesso** [comment]
Thanks for pointing this out, the project has been rebuilt with React, you can check my repo for update. Thanks

**Comment by georgeben** [comment]
You're welcome
